import type { Transaction, Budget, CategoryInfo } from "./types";

// Category configuration
export const categoryConfig: Record<string, CategoryInfo> = {
  salary: { name: "Salary", icon: "Briefcase", color: "rgb(34, 197, 94)" },
  freelance: { name: "Freelance", icon: "Laptop", color: "rgb(59, 130, 246)" },
  investment: {
    name: "Investment",
    icon: "TrendingUp",
    color: "rgb(168, 85, 247)",
  },
  "other-income": {
    name: "Other Income",
    icon: "Plus",
    color: "rgb(14, 165, 233)",
  },
  food: { name: "Food & Dining", icon: "Utensils", color: "rgb(249, 115, 22)" },
  transport: { name: "Transport", icon: "Car", color: "rgb(239, 68, 68)" },
  utilities: { name: "Utilities", icon: "Zap", color: "rgb(234, 179, 8)" },
  entertainment: {
    name: "Entertainment",
    icon: "Film",
    color: "rgb(236, 72, 153)",
  },
  shopping: {
    name: "Shopping",
    icon: "ShoppingBag",
    color: "rgb(139, 92, 246)",
  },
  healthcare: { name: "Healthcare", icon: "Heart", color: "rgb(20, 184, 166)" },
  education: {
    name: "Education",
    icon: "GraduationCap",
    color: "rgb(99, 102, 241)",
  },
  rent: { name: "Rent", icon: "Home", color: "rgb(244, 63, 94)" },
  "other-expense": {
    name: "Other",
    icon: "MoreHorizontal",
    color: "rgb(107, 114, 128)",
  },
};

// Mock transactions
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    type: "income",
    category: "salary",
    amount: 5500,
    description: "Monthly Salary",
    date: new Date(2026, 1, 1),
    tags: ["work", "regular"],
  },
  {
    id: "2",
    type: "expense",
    category: "rent",
    amount: 1500,
    description: "February Rent",
    date: new Date(2026, 1, 1),
    tags: ["housing", "fixed"],
  },
  {
    id: "3",
    type: "expense",
    category: "food",
    amount: 45.5,
    description: "Grocery Shopping",
    date: new Date(2026, 1, 3),
    tags: ["essentials"],
  },
  {
    id: "4",
    type: "expense",
    category: "transport",
    amount: 60,
    description: "Gas Station",
    date: new Date(2026, 1, 5),
  },
  {
    id: "5",
    type: "income",
    category: "freelance",
    amount: 850,
    description: "Website Design Project",
    date: new Date(2026, 1, 7),
    tags: ["freelance", "design"],
  },
  {
    id: "6",
    type: "expense",
    category: "utilities",
    amount: 120,
    description: "Electricity Bill",
    date: new Date(2026, 1, 8),
    tags: ["bills", "fixed"],
  },
  {
    id: "7",
    type: "expense",
    category: "entertainment",
    amount: 55,
    description: "Movie Night & Dinner",
    date: new Date(2026, 1, 10),
    tags: ["leisure"],
  },
  {
    id: "8",
    type: "expense",
    category: "food",
    amount: 25.8,
    description: "Restaurant Lunch",
    date: new Date(2026, 1, 12),
  },
  {
    id: "9",
    type: "expense",
    category: "shopping",
    amount: 180,
    description: "Clothing Store",
    date: new Date(2026, 1, 14),
    tags: ["fashion"],
  },
  {
    id: "10",
    type: "expense",
    category: "healthcare",
    amount: 90,
    description: "Doctor Appointment",
    date: new Date(2026, 1, 15),
    tags: ["health"],
  },
  {
    id: "11",
    type: "income",
    category: "investment",
    amount: 125,
    description: "Stock Dividends",
    date: new Date(2026, 1, 16),
    tags: ["passive"],
  },
  {
    id: "12",
    type: "expense",
    category: "transport",
    amount: 45,
    description: "Uber Rides",
    date: new Date(2026, 1, 17),
  },
  {
    id: "13",
    type: "expense",
    category: "food",
    amount: 68.9,
    description: "Grocery Shopping",
    date: new Date(2026, 1, 18),
  },
  {
    id: "14",
    type: "expense",
    category: "utilities",
    amount: 55,
    description: "Internet Bill",
    date: new Date(2026, 1, 19),
    tags: ["bills", "fixed"],
  },
  {
    id: "15",
    type: "expense",
    category: "entertainment",
    amount: 35,
    description: "Streaming Subscriptions",
    date: new Date(2026, 1, 20),
    tags: ["subscription"],
  },
];

// Mock budgets
export const mockBudgets: Budget[] = [
  {
    id: "1",
    category: "food",
    limit: 500,
    spent: 140.2,
    period: "monthly",
  },
  {
    id: "2",
    category: "transport",
    limit: 300,
    spent: 105,
    period: "monthly",
  },
  {
    id: "3",
    category: "entertainment",
    limit: 200,
    spent: 90,
    period: "monthly",
  },
  {
    id: "4",
    category: "shopping",
    limit: 400,
    spent: 180,
    period: "monthly",
  },
  {
    id: "5",
    category: "utilities",
    limit: 250,
    spent: 175,
    period: "monthly",
  },
  {
    id: "6",
    category: "healthcare",
    limit: 150,
    spent: 90,
    period: "monthly",
  },
];
